name: First Workflow
on: worfklow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world!"
      - name: print goodby
        run: echo "done"
        
